apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datagen-1
  template:
      metadata:
        labels:
          app: datagen-1
      spec:
        containers:
        - name: datagen-1
          image: gcr.io/level-approach-382012/datagen_image:latest